# TRAVIS CONFIG

language: cpp
sudo: required
compiler:
- gcc
os:
- osx
  
script: 
  - echo $PATH
  - echo $HOME
  - g++ -o run.exe hello.cpp 
  
after_success:
  - ./run.exe > logfile.log
  - cat logfile.log
  - echo "Email Added"
  
nnotifications:
  email:
    recipients:
      - anthony.michel@free.fr
    on_success: always # default: change
    on_failure: always # default: always
