#language: python
language: cpp

language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
  
script: 
  - echo $PATH
  - echo $HOME
  - g++ -o run.exe hello.cpp 
  
after_success:
  - ./run.exe > logfile.log
  - cat logfile.log
